name: Java CI with Maven

on:
  push:
    branches:
      - "main"
      - "dev"
      - "testing"  # Include the testing branch
  pull_request:
    branches:
      - "main"
      - "dev"
      - "testing"  # Include the testing branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Run Unit Tests
      - name: Run tests with Maven
        run: mvn test

      # Generate Jacoco code coverage report
      - name: Generate Jacoco coverage report
        run: mvn jacoco:report

      # Upload Jacoco report as a build artifact
      - name: Upload Jacoco report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco
