name: Java CI with Merge Prompt

on:
  push:
    branches:
      - "main"
      - "dev"
      - "testing"
  pull_request:
    branches:
      - "main"
      - "dev"
      - "testing"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests with Maven
        run: mvn test

      - name: Generate Jacoco coverage report
        run: mvn jacoco:report

      - name: Upload Jacoco report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - name: Notify for Merge
        run: |
          echo "::set-output name=message::The 'testing' branch passed all tests and is ready to be merged into 'main'."
        id: notify

      - name: Create Comment on PR (Optional)
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'The `testing` branch has passed all checks and is ready for merging into `main`!'
            })
